#!/usr/bin/env php
<?php
// File: fossil

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Autoalias\Component\Console\Command\ChangeDirectoryCommand;

$command = new ChangeDirectoryCommand();

$application = new Application('Autoalias', '1.0.0');
$application->add($command);
$application->run();