#!/usr/bin/env php
<?php
// File: fossil

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\QuestionHelper;
use Autoalias\Component\Console\Command\AutoAliasExecuteCommand;
use Autoalias\Component\Console\Command\AutoAliasMessageCommand;

$application = new Application('Autoalias', '1.0.0');
$application->add(new AutoAliasExecuteCommand());
$application->add(new AutoAliasMessageCommand());
$application->run();
